# Generated by Django 3.0 on 2019-12-13 07:03

from django.db import migrations, models
import mdeditor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=uuid.UUID('a958ec4a-667e-4595-8367-0fe70ef3357d'), max_length=40, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=400)),
                ('content_path', mdeditor.fields.MDTextField()),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
    ]
